name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    strategy:
      matrix:
        - os: {"ubuntu-22.04", "macos-14", "windows-2022"}
        - python-version: ["3.12"]
        include:
          - os: "ubuntu-22.04"
            python-version: "3.9"
    runs-on: ${{matrix.os}}
    # runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - run: pip install tox
    - name: Lint the code
      run: tox -e lint