name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        - os: {"ubuntu-22.04", "macos-14", "windows-2022"}
        - python-version: ["3.12"]
        include:
          - os: "ubuntu-22.04"
            python-version: "3.9"
     runs-on: ${{matrix.os}}

     steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"
          - run: pip install tox
          - name: Tests the code
            run: tox -e tests