name: Tests

on:
    push:
        branches: [main]
    pull_request:
        # Check all PR

jobs:
    tests:
        strategy:
            matrix:
                os: ["ubuntu-22.04", "macos-15", "windows-2025"]
                python-version: ["3.12"]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4
            - name: Set up python
              uses: actions/setup-python@v2
              with:
                python-version:  ${{ matrix.python-version }}
            - run: pip install tox
            - name: Run the tests
              run: tox -e tests

